sudo:
  - required

services:
  - docker

befor_install:
  - docker pull andrejlevkovitch/ubuntu_qt_boost:latest
  - docker run andrejlevkovitch/ubuntu_qt_boost:latest

script:
  - docker build -t test_docker .
