sudo:
  - required

services:
  - docker

before_install:
  - docker pull andrejlevkovitch/ubuntu_qt_boost:second
  - docker run andrejlevkovitch/ubuntu_qt_boost:second

script:
  - docker build -t test_docker .
