// main.cpp

#include "brick_game.hpp"
#include "general_window.hpp"
#include <QApplication>
#include <QFile>
#include <QLatin1String>
#include <exception>

/// generated by cmake
#include "config.h"
#include "messageToFile.hpp"
#include <QDebug>

#ifdef Boost_FOUND
#include <boost/filesystem.hpp>
#else
#include <experimental/filesystem>
#endif

int main(int argc, char *argv[]) {
  ::QApplication app(argc, argv);
  {
    /// depends of config.h
#ifdef DEBUG_IN_FILE
    ::QFile file(file_protocol_name);
    if (file.open(::QIODevice::WriteOnly)) {
      file.close();
      ::qInstallMessageHandler(messageToFile);
    }
#endif

    /// depends of config.h
#ifdef Boost_FOUND
    ::qDebug() << "Using boost";
    if (!boost::filesystem::exists(brick_game::HOME.toStdString().c_str())) {
      ::qDebug() << "directory whith game files dosn't exists";
      if (boost::filesystem::create_directory(
              brick_game::HOME.toStdString().c_str())) {
        ::qDebug() << "directory for game files created";
      }
    }
#else
    ::qDebug() << "Using c++17";
    if (!std::experimental::filesystem::exists(
            brick_game::HOME.toStdString().c_str())) {
      ::qDebug() << "directory whith game files dosn't exists";
      if (std::experimental::filesystem::create_directory(
              brick_game::HOME.toStdString().c_str())) {
        ::qDebug() << "directory for game files created";
      }
    }
#endif
  }

  ::QFile file{":/style/default.qss"};
  if (file.open(::QFile::ReadOnly)) {
    ::qDebug() << "open style file";
    app.setStyleSheet(file.readAll());
    file.close();
  }

  brick_game::general_window brick_game_window;
  brick_game_window.show();

  return app.exec();
}
